export const categoryConstance = {
  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
  GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
};
export const brandConstance = {
  GET_ALL_BRANDS_REQUEST: "GET_ALL_BRANDS_REQUEST",
  GET_ALL_BRANDS_SUCCESS: "GET_ALL_BRANDS_SUCCESS",
  GET_ALL_BRANDS_FAILURE: "GET_ALL_BRANDS_FAILURE",
};
export const getAllProducts = {
  GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",
};
export const getProductById = {
  GET_PRODUCT_BY_ID_REQUEST: "GET_PRODUCT_BY_ID_REQUEST",
  GET_PRODUCT_BY_ID_SUCCESS: "GET_PRODUCT_BY_ID_SUCCESS",
  GET_PRODUCT_BY_ID_FAILURE: "GET_PRODUCT_BY_ID_FAILURE",
};
export const getRelatedProduct = {
  GET_RELATED_PRODUCT_REQUEST: "GET_RELATED_PRODUCT_REQUEST",
  GET_RELATED_PRODUCT_SUCCESS: "GET_RELATED_PRODUCT_SUCCESS",
  GET_RELATED_PRODUCT_FAILURE: "GET_RELATED_PRODUCT_FAILURE",
};
export const Signing = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
};
export const Signup = {
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
};
export const Logout = {
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};
export const cartConstance = {
  ADD_TO_CART: "ADD_TO_CART",
  INCREASE_CART_QTY: "INCREASE_CART",
  DECREASE_CART_QTY: "DECREASE_CART",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
  USER_CART_REQ_TO_DB: "USER_CART_REQ_TO_DB",
  USER_CART_SUC_TO_DB: "USER_CART_SUC_TO_DB",
  USER_CART_FAI_TO_DB: "USER_CART_FAI_TO_DB",
  GET_CART_ITEM_FROM_DB: "GET_CART_ITEM_FROM_DB",
};
export const productBySearch = {
  SEARCH_PRODUCT_SUCCESS: "SEARCH_PRODUCT_SUCCESS",
  SEARCH_PRODUCT_FAILURE: "SEARCH_PRODUCT_FAILURE",
};
